name = "ignitia-theme"
description = "A modern, blazing fast theme for Ignitia Rust Web Framework"
license = "MIT"
homepage = "https://github.com/AarambhDevHub/ignitia"
min_version = "0.17.0"
demo = ""

[author]
name = "Darshan Vichhi"
homepage = "https://github.com/AarambhDevHub"

[extra]
